name: Build Image On Release

on:
  push:
    tags: 
      - 'v*'
      - 'update-base'
  pull_request:
    branches:
      - 'main' 
    types: [ assigned ]

env:
  DOCKERHUB_SLUG: thespad/py-kms
  GHCR_SLUG: ghcr.io/thespad/py-kms

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.5
      -  
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: |
            ${{ env.DOCKERHUB_SLUG }}
            ${{ env.GHCR_SLUG }}
          labels: |
            org.opencontainers.image.title=py-kms
            org.opencontainers.image.description=py-kms
            org.opencontainers.image.vendor=TheSpad
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Build and push
        uses: docker/bake-action@v1.6.0
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.docker_meta.outputs.bake-file }}
          targets: image-all
          push: true
